# coding: utf-8

"""
    NuMind extraction platform

    API to interact with NuMind models.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from numind.openapi_client.models.token_code_request import TokenCodeRequest

class TestTokenCodeRequest(unittest.TestCase):
    """TokenCodeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TokenCodeRequest:
        """Test TokenCodeRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TokenCodeRequest`
        """
        model = TokenCodeRequest()
        if include_optional:
            return TokenCodeRequest(
                code = '',
                redirect_uri = '',
                type = 'ai.numind.extract.shared.TokenCodeRequest'
            )
        else:
            return TokenCodeRequest(
                code = '',
                redirect_uri = '',
                type = 'ai.numind.extract.shared.TokenCodeRequest',
        )
        """

    def testTokenCodeRequest(self):
        """Test TokenCodeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
