# coding: utf-8

"""
    NuMind extraction platform

    API to interact with NuMind models.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from numind.openapi_client.models.inference_response import InferenceResponse

class TestInferenceResponse(unittest.TestCase):
    """InferenceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InferenceResponse:
        """Test InferenceResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InferenceResponse`
        """
        model = InferenceResponse()
        if include_optional:
            return InferenceResponse(
                result = '',
                document_info = None,
                tokens = 56
            )
        else:
            return InferenceResponse(
                result = '',
                document_info = None,
                tokens = 56,
        )
        """

    def testInferenceResponse(self):
        """Test InferenceResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
