# coding: utf-8

"""
    NuMind extraction platform

    API to interact with NuMind models.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from numind.openapi_client.api.authentication_api import AuthenticationApi


class TestAuthenticationApi(unittest.TestCase):
    """AuthenticationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthenticationApi()

    def tearDown(self) -> None:
        pass

    def test_delete_api_auth_user_tokens_usertokenid(self) -> None:
        """Test case for delete_api_auth_user_tokens_usertokenid

        """
        pass

    def test_get_api_auth(self) -> None:
        """Test case for get_api_auth

        """
        pass

    def test_get_api_auth_me(self) -> None:
        """Test case for get_api_auth_me

        """
        pass

    def test_get_api_auth_user_tokens(self) -> None:
        """Test case for get_api_auth_user_tokens

        """
        pass

    def test_post_api_auth_logout(self) -> None:
        """Test case for post_api_auth_logout

        """
        pass

    def test_post_api_auth_token(self) -> None:
        """Test case for post_api_auth_token

        """
        pass

    def test_post_api_auth_user_tokens(self) -> None:
        """Test case for post_api_auth_user_tokens

        """
        pass

    def test_put_api_auth_user_tokens_usertokenid(self) -> None:
        """Test case for put_api_auth_user_tokens_usertokenid

        """
        pass


if __name__ == '__main__':
    unittest.main()
