# coding: utf-8

"""
    NuMind extraction platform

    API to interact with NuMind models.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from numind.openapi_client.api.reference_api import ReferenceApi


class TestReferenceApi(unittest.TestCase):
    """ReferenceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ReferenceApi()

    def tearDown(self) -> None:
        pass

    def test_delete_api_reference_projects_projectid(self) -> None:
        """Test case for delete_api_reference_projects_projectid

        """
        pass

    def test_delete_api_reference_projects_projectid_examples_exampleid(self) -> None:
        """Test case for delete_api_reference_projects_projectid_examples_exampleid

        """
        pass

    def test_delete_api_reference_projects_projectid_results_historyid(self) -> None:
        """Test case for delete_api_reference_projects_projectid_results_historyid

        """
        pass

    def test_get_api_reference_documents_documentid(self) -> None:
        """Test case for get_api_reference_documents_documentid

        """
        pass

    def test_get_api_reference_documents_documentid_content(self) -> None:
        """Test case for get_api_reference_documents_documentid_content

        """
        pass

    def test_get_api_reference_projects(self) -> None:
        """Test case for get_api_reference_projects

        """
        pass

    def test_get_api_reference_projects_projectid(self) -> None:
        """Test case for get_api_reference_projects_projectid

        """
        pass

    def test_get_api_reference_projects_projectid_examples(self) -> None:
        """Test case for get_api_reference_projects_projectid_examples

        """
        pass

    def test_get_api_reference_projects_projectid_examples_exampleid(self) -> None:
        """Test case for get_api_reference_projects_projectid_examples_exampleid

        """
        pass

    def test_get_api_reference_projects_projectid_results(self) -> None:
        """Test case for get_api_reference_projects_projectid_results

        """
        pass

    def test_get_api_reference_projects_projectid_results_historyid(self) -> None:
        """Test case for get_api_reference_projects_projectid_results_historyid

        """
        pass

    def test_post_api_reference_documents_file(self) -> None:
        """Test case for post_api_reference_documents_file

        """
        pass

    def test_post_api_reference_documents_text(self) -> None:
        """Test case for post_api_reference_documents_text

        """
        pass

    def test_post_api_reference_infer_template(self) -> None:
        """Test case for post_api_reference_infer_template

        """
        pass

    def test_post_api_reference_projects(self) -> None:
        """Test case for post_api_reference_projects

        """
        pass

    def test_post_api_reference_projects_projectid_duplicate(self) -> None:
        """Test case for post_api_reference_projects_projectid_duplicate

        """
        pass

    def test_post_api_reference_projects_projectid_examples(self) -> None:
        """Test case for post_api_reference_projects_projectid_examples

        """
        pass

    def test_post_api_reference_projects_projectid_infer_document_documentid(self) -> None:
        """Test case for post_api_reference_projects_projectid_infer_document_documentid

        """
        pass

    def test_post_api_reference_projects_projectid_infer_file(self) -> None:
        """Test case for post_api_reference_projects_projectid_infer_file

        """
        pass

    def test_post_api_reference_projects_projectid_infer_text(self) -> None:
        """Test case for post_api_reference_projects_projectid_infer_text

        """
        pass

    def test_post_api_reference_projects_projectid_lock(self) -> None:
        """Test case for post_api_reference_projects_projectid_lock

        """
        pass

    def test_post_api_reference_projects_projectid_results(self) -> None:
        """Test case for post_api_reference_projects_projectid_results

        """
        pass

    def test_post_api_reference_projects_projectid_unlock(self) -> None:
        """Test case for post_api_reference_projects_projectid_unlock

        """
        pass

    def test_put_api_reference_projects_projectid(self) -> None:
        """Test case for put_api_reference_projects_projectid

        """
        pass

    def test_put_api_reference_projects_projectid_examples_exampleid(self) -> None:
        """Test case for put_api_reference_projects_projectid_examples_exampleid

        """
        pass

    def test_put_api_reference_projects_projectid_results_historyid(self) -> None:
        """Test case for put_api_reference_projects_projectid_results_historyid

        """
        pass


if __name__ == '__main__':
    unittest.main()
