# coding: utf-8

"""
    NuMind extraction platform

    API to interact with NuMind models.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from numind.openapi_client.models.text_info import TextInfo

class TestTextInfo(unittest.TestCase):
    """TextInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TextInfo:
        """Test TextInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TextInfo`
        """
        model = TextInfo()
        if include_optional:
            return TextInfo(
                document_id = '',
                file_name = '',
                text = '',
                type = 'text'
            )
        else:
            return TextInfo(
                document_id = '',
                text = '',
                type = 'text',
        )
        """

    def testTextInfo(self):
        """Test TextInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
