# coding: utf-8

"""
    NuMind extraction platform

    API to interact with NuMind models.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from numind.openapi_client.models.example_response import ExampleResponse

class TestExampleResponse(unittest.TestCase):
    """ExampleResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExampleResponse:
        """Test ExampleResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExampleResponse`
        """
        model = ExampleResponse()
        if include_optional:
            return ExampleResponse(
                id = '',
                project_id = '',
                owner_user = '',
                document_info = None,
                result = '',
                created_at = '',
                updated_at = ''
            )
        else:
            return ExampleResponse(
                id = '',
                project_id = '',
                owner_user = '',
                document_info = None,
                result = '',
                created_at = '',
                updated_at = '',
        )
        """

    def testExampleResponse(self):
        """Test ExampleResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
