# coding: utf-8

"""
    NuMind extraction platform

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, Dict, List, Optional
from numind.openapi_client.models.bool1 import Bool1
from numind.openapi_client.models.num1 import Num1
from numind.openapi_client.models.obj1 import Obj1
from numind.openapi_client.models.str1 import Str1
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

INFONODE_ONE_OF_SCHEMAS = ["Arr1", "Bool1", "Num1", "Obj1", "Str1", "object"]

class InfoNode(BaseModel):
    """
    InfoNode
    """
    # data type: Arr1
    oneof_schema_1_validator: Optional[Arr1] = None
    # data type: Bool1
    oneof_schema_2_validator: Optional[Bool1] = None
    # data type: object
    oneof_schema_3_validator: Optional[Dict[str, Any]] = None
    # data type: Num1
    oneof_schema_4_validator: Optional[Num1] = None
    # data type: Obj1
    oneof_schema_5_validator: Optional[Obj1] = None
    # data type: Str1
    oneof_schema_6_validator: Optional[Str1] = None
    actual_instance: Optional[Union[Arr1, Bool1, Num1, Obj1, Str1, object]] = None
    one_of_schemas: Set[str] = { "Arr1", "Bool1", "Num1", "Obj1", "Str1", "object" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = InfoNode.model_construct()
        error_messages = []
        match = 0
        # validate data type: Arr1
        if not isinstance(v, Arr1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Arr1`")
        else:
            match += 1
        # validate data type: Bool1
        if not isinstance(v, Bool1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Bool1`")
        else:
            match += 1
        # validate data type: object
        try:
            instance.oneof_schema_3_validator = v
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # validate data type: Num1
        if not isinstance(v, Num1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Num1`")
        else:
            match += 1
        # validate data type: Obj1
        if not isinstance(v, Obj1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Obj1`")
        else:
            match += 1
        # validate data type: Str1
        if not isinstance(v, Str1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Str1`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in InfoNode with oneOf schemas: Arr1, Bool1, Num1, Obj1, Str1, object. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in InfoNode with oneOf schemas: Arr1, Bool1, Num1, Obj1, Str1, object. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into Arr1
        try:
            instance.actual_instance = Arr1.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Bool1
        try:
            instance.actual_instance = Bool1.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into object
        try:
            # validation
            instance.oneof_schema_3_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.oneof_schema_3_validator
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Num1
        try:
            instance.actual_instance = Num1.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Obj1
        try:
            instance.actual_instance = Obj1.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Str1
        try:
            instance.actual_instance = Str1.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into InfoNode with oneOf schemas: Arr1, Bool1, Num1, Obj1, Str1, object. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into InfoNode with oneOf schemas: Arr1, Bool1, Num1, Obj1, Str1, object. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], Arr1, Bool1, Num1, Obj1, Str1, object]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())

from numind.openapi_client.models.arr1 import Arr1
# TODO: Rewrite to not use raise_errors
InfoNode.model_rebuild(raise_errors=False)

