# coding: utf-8

"""
    NuMind extraction platform

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, Dict, List, Optional
from numind.openapi_client.models.enum import Enum
from numind.openapi_client.models.multi_enum import MultiEnum
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

SCHEMANODE_ONE_OF_SCHEMAS = ["Arr", "Enum", "MultiEnum", "Obj", "object"]

class SchemaNode(BaseModel):
    """
    SchemaNode
    """
    # data type: Arr
    oneof_schema_1_validator: Optional[Arr] = None
    # data type: object
    oneof_schema_2_validator: Optional[Dict[str, Any]] = None
    # data type: object
    oneof_schema_3_validator: Optional[Dict[str, Any]] = None
    # data type: Enum
    oneof_schema_4_validator: Optional[Enum] = None
    # data type: object
    oneof_schema_5_validator: Optional[Dict[str, Any]] = None
    # data type: MultiEnum
    oneof_schema_6_validator: Optional[MultiEnum] = None
    # data type: object
    oneof_schema_7_validator: Optional[Dict[str, Any]] = None
    # data type: Obj
    oneof_schema_8_validator: Optional[Obj] = None
    # data type: object
    oneof_schema_9_validator: Optional[Dict[str, Any]] = None
    # data type: object
    oneof_schema_10_validator: Optional[Dict[str, Any]] = None
    actual_instance: Optional[Union[Arr, Enum, MultiEnum, Obj, object]] = None
    one_of_schemas: Set[str] = { "Arr", "Enum", "MultiEnum", "Obj", "object" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = SchemaNode.model_construct()
        error_messages = []
        match = 0
        # validate data type: Arr
        if not isinstance(v, Arr):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Arr`")
        else:
            match += 1
        # validate data type: object
        try:
            instance.oneof_schema_2_validator = v
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # validate data type: object
        try:
            instance.oneof_schema_3_validator = v
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # validate data type: Enum
        if not isinstance(v, Enum):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Enum`")
        else:
            match += 1
        # validate data type: object
        try:
            instance.oneof_schema_5_validator = v
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # validate data type: MultiEnum
        if not isinstance(v, MultiEnum):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MultiEnum`")
        else:
            match += 1
        # validate data type: object
        try:
            instance.oneof_schema_7_validator = v
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # validate data type: Obj
        if not isinstance(v, Obj):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Obj`")
        else:
            match += 1
        # validate data type: object
        try:
            instance.oneof_schema_9_validator = v
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # validate data type: object
        try:
            instance.oneof_schema_10_validator = v
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in SchemaNode with oneOf schemas: Arr, Enum, MultiEnum, Obj, object. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in SchemaNode with oneOf schemas: Arr, Enum, MultiEnum, Obj, object. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into Arr
        try:
            instance.actual_instance = Arr.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into object
        try:
            # validation
            instance.oneof_schema_2_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.oneof_schema_2_validator
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into object
        try:
            # validation
            instance.oneof_schema_3_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.oneof_schema_3_validator
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Enum
        try:
            instance.actual_instance = Enum.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into object
        try:
            # validation
            instance.oneof_schema_5_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.oneof_schema_5_validator
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into MultiEnum
        try:
            instance.actual_instance = MultiEnum.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into object
        try:
            # validation
            instance.oneof_schema_7_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.oneof_schema_7_validator
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Obj
        try:
            instance.actual_instance = Obj.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into object
        try:
            # validation
            instance.oneof_schema_9_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.oneof_schema_9_validator
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into object
        try:
            # validation
            instance.oneof_schema_10_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.oneof_schema_10_validator
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into SchemaNode with oneOf schemas: Arr, Enum, MultiEnum, Obj, object. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into SchemaNode with oneOf schemas: Arr, Enum, MultiEnum, Obj, object. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], Arr, Enum, MultiEnum, Obj, object]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())

from numind.openapi_client.models.arr import Arr
from numind.openapi_client.models.obj import Obj
# TODO: Rewrite to not use raise_errors
SchemaNode.model_rebuild(raise_errors=False)

