# coding: utf-8

"""
    NuMind extraction platform

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from numind.openapi_client.models.invalid_information import InvalidInformation

class TestInvalidInformation(unittest.TestCase):
    """InvalidInformation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InvalidInformation:
        """Test InvalidInformation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InvalidInformation`
        """
        model = InvalidInformation()
        if include_optional:
            return InvalidInformation(
                information = '',
                error = '',
                type = 'string'
            )
        else:
            return InvalidInformation(
                information = '',
                error = '',
                type = 'string',
        )
        """

    def testInvalidInformation(self):
        """Test InvalidInformation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
