# coding: utf-8

"""
NuMind extraction platform

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from numind.openapi_client.models.schema_node import SchemaNode


class TestSchemaNode(unittest.TestCase):
    """SchemaNode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SchemaNode:
        """Test SchemaNode
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `SchemaNode`
        """
        model = SchemaNode()
        if include_optional:
            return SchemaNode(
                var_schema = None,
                values = [
                    ''
                    ],
                schemas = {
                    'key' : null
                    }
            )
        else:
            return SchemaNode(
                var_schema = None,
                schemas = {
                    'key' : null
                    },
        )
        """

    def testSchemaNode(self):
        """Test SchemaNode"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
